apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallengeapp-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: techchallengeapp-deployment
      visualize: "true"
  template:
    metadata:
      labels:
        app: techchallengeapp-deployment
        visualize: "true"
    spec:
      containers:
        - name: techchallengeapp-deployment
          image: amazonaws.com/restaurante-service 
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
          - containerPort: 8080

