apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: techchallengeapp-service
  spec:
    type: NodePort
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: techchallengeapp-deployment

- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: techchallengeapp-hpa
    namespace: default
  spec:
    targetCPUUtilizationPercentage: 70
    maxReplicas: 1
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: techchallengeapp-deployment
      
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
    labels:
      app: postgres
  spec:
    type: NodePort
    ports:
    - port: 5432
    selector:
    app: postgres