version: '3'

services:
  api:
    build:
      context: .
      target: development
    command: npm run dev
    env_file:
      - .env
    ports:
      - 3004:3004
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
  postgres:
    image: bitnami/postgresql:latest 
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - "5432:5432"